TYPO3:
  TYPO3CR:
    contentDimensions:
      'language':
        default: 'en_US'
        defaultPreset: 'en_US'
        presets:
          'all': ~
          'en_US':
            label: 'English (US)'
            values: ['en_US']
            uriSegment: 'en'
          'en_UK': ~
          'de': ~
          'fr': ~
          'nl': ~
          'dk': ~
          'lv': ~